In [41]:
import torch
import numpy as np

## Создание тензоров

In [3]:
v = torch.empty(2,3)
V = torch.empty_like(v)

In [4]:
v

tensor([[ 3.3631e-44,  5.0850e+31, -5.2426e+17],
        [ 4.5623e-41,  1.4013e-45,  5.2839e-11]])

In [5]:
x = torch.tensor([1.,2.,3.], dtype=torch.float16)

In [6]:
x.dtype

torch.float16

In [7]:
y = torch.tensor([0.5, 0.3],dtype=torch.double)

In [8]:
y.shape

torch.Size([2])

In [9]:
Y = y.long()

In [10]:
Y

tensor([0, 0])

In [43]:
z = np.random.rand(3,2)
Z = torch.from_numpy(z)

## Инициализация

In [11]:
z = torch.zeros(2,3)

In [12]:
yy = torch.zeros_like(y)

In [13]:
torch.full((2,3),1.5)

tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])

In [14]:
torch.randn(3,2)

tensor([[ 0.2984, -0.5755],
        [ 0.6799,  1.3771],
        [ 0.0274, -0.4682]])

In [15]:
torch.arange(4)

tensor([0, 1, 2, 3])

In [16]:
torch.arange(2,10,3)

tensor([2, 5, 8])

In [17]:
torch.randperm(2)

tensor([1, 0])

In [18]:
torch.randint(1,10,(3,2))

tensor([[9, 9],
        [1, 2],
        [9, 1]])

## Управление памятью

In [19]:
x = torch.ones(1)                        # вектор из одной компоненты
y = x.exp()                              # разная память:
print(x)
y[0]=2;  print(x.item())       # tensor([1.])      1.0
 
y = x.exp_()                             # одна память:
print(x);  y[0]=2;  print(x.item()) 

tensor([1.])
1.0
tensor([2.7183])
2.0


In [20]:
x = torch.empty(2, 3).fill_(-1)          # матрица из -1
x.zero_()   

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
y = x                                    # y и z - один объект
y = x.clone()                            # копирование 
 
y.copy_(x)                               # копирует в себя x (broadcastable)
y = torch.empty_like(x).copy_(x)         # выделяем память и копируем 

## Операции

In [22]:
x1, x2 = torch.ones(2,3),  torch.ones(2,3)  
 
x1[0]   = 2           # меням первую строчку на 2 [ [2., 2., 2.],  [1., 1., 1.]]
x2[:,1] = 3           # меням вторую колонку на 3 [ [1., 3., 1.],  [1., 3., 1.]]
 
y = x1 + x2           # складываем                [ [3., 5., 3.],  [2., 4., 2.]]

In [23]:
x += y
x.add_(y)             # к тензору x добавили y (инкриментация)
x.add_(y, alpha=2.0)  # x += 2*y (так быстрее для больших тензоров)
 
x *= y
x.mul_(y)

tensor([[108., 500., 108.],
        [ 32., 256.,  32.]])

In [24]:
a = torch.ByteTensor(2,3).random_() # случайные байты [[185,  16, 242], [223, 147, 202]]
 
print(a > 128)                      # [[ True, False,  True], [ True,  True,  True]]
a[a > 128]                          # [185, 242, 223, 147, 202] - элементы, большие 128

tensor([[False,  True, False],
        [ True, False, False]])


tensor([232, 169], dtype=torch.uint8)

In [25]:
X = torch.arange(10)                # [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Y = -X                              # [ 0,-1,-2,-3,-4,-5,-6,-7,-8,-9]
 
idx = torch.randperm(X.shape[0])    # перестановка индексов
X = X[idx]                          # [ 4, 9, 7, 3, 2, 0, 5, 6, 1, 8]
Y = Y[idx]                          # [-4,-9,-7,-3,-2, 0,-5,-6,-1,-8]                          

In [26]:
x1 = torch.arange(-3,0)             # [-3, -2, -1]
x2 = torch.arange(3)                # [ 0,  1,  2]
 
torch.cat([x1, x2], dim=0)          #  [-3, -2, -1,  0,  1,  2]    конкатенация 
torch.stack([x1, x2])               # [[-3, -2, -1], [ 0,  1,  2]]

tensor([[-3, -2, -1],
        [ 0,  1,  2]])

## Тензорные операции

In [27]:
u = torch.tensor([1,2,3],dtype=torch.float)
t = u.dot(u)                # cкалярное умножение - только 1D векторов

x.mv(u)                 # матрица на вектор: (n,s) (s)   = (n)
x.mm(x.T)                 # только 2D матриц : (n,s) (s,m) = (n,m)
x.matmul(x.T)             # аналог из numpy: (j,1, n,s) (k, s,m) = (j,k, n,m)

tensor([[273328., 134912.],
        [134912.,  67584.]])

In [28]:
x = torch.Tensor([[2,1,3],
                  [1,2,1]])
x.sum(1)                # [6., 4.]   cумма     
x.mean(1)               # [2., 1.33] cреднее   
x.prod(1)               # [6., 2.]   произведение 
 
x.argmin(1)             # [1, 2]
 
v,i = x.topk(2, dim=0)  # 2 наибольших значений и их индексов

In [29]:
v,i= x.sort(dim=0) 
i

tensor([[1, 0, 1],
        [0, 1, 0]])

## Изменение формы

In [30]:
torch.arange(6).view(2,3)         #    tensor([[0, 1, 2],
torch.arange(6).reshape(2,3)      #            [3, 4, 5]])

tensor([[0, 1, 2],
        [3, 4, 5]])

In [31]:
a, b = torch.zeros(2,5), torch.zeros(10)
b.view_as(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
z = x.t()                              # сам x не меняется
z = x.t_()                             # меняется x

In [33]:
x.transpose(0, 1)                      # перестановка осей 1 и 2

tensor([[2., 1., 3.],
        [1., 2., 1.]])

In [34]:
x = torch.randn(3, 5)               
x.permute(1, 0) == x.t()               # эквивалентно транспонированию
 
x = torch.randn(2, 3, 5)
x.permute(2, 0, 1).size()              # torch.Size([5, 2, 3])

torch.Size([5, 2, 3])

GPU

In [35]:
x1 = torch.eye(10000)
y1 = torch.eye(10000)
z1 = x1.mm(y1)                         

In [36]:
z1

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [37]:
torch.cuda.device_count()              # число доступных GPU
 
cpu = torch.device("cpu")
gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [38]:
# x1 = torch.eye(10000, device = gpu)
# y1 = torch.eye(10000, device = gpu)
# z1 = x1.mm(y1)                         # 0.04s

In [39]:
# x1 = torch.eye(10000).to(gpu)
# y1 = torch.eye(10000).to(gpu)
# z1 = x1.mm(y1).to(cpu)  

In [ ]:
# torch.cuda.empty_cache()